title: ULRICH WHITMAN DJEUTSA NODEM
LOGO: 133933639390590177.jpg
description: création d'un portfoflio et blog qui présente mes projets en analytique d'affaire, en exploitation, traitement, analyse et valorisation des données.
theme: prédiction d'un défaut de crédit en utilisant une regression logistique 
